---
# tasks file for failover

- name: Install SqlServer PsModule
  tags: failover
  community.windows.win_psmodule:
    name: SqlServer
    state: present
    allow_clobber: true

- name: Perform health checks
  tags: node_health
  when: failover_require_healthcheck is true
  any_errors_fatal: true
  delegate_to: '{{ failover_current_primary_replica }}'
  block:
    - name: Enable Cluster
      ansible.builtin.include_role:
        name: node_health
      vars:
        node_health_desired_replica_role: SecondaryReplica

- name: Initiate failover
  tags: failover
  become: true
  become_user: SYSTEM
  register: result
  ansible.windows.win_shell: |
    {{ lookup('ansible.builtin.file', 'Set-MssqlPrimaryReplica.ps1') }}
    Set-MssqlPrimaryReplica {{ mssql_ag_name }} -Verbose
  failed_when: result.stderr | length > 0
